title = "P U T 1 0 1"
base_url = "https://put101.xyz"
theme = "anpu"

compile_sass = true

build_search_index = false

output_dir = "docs"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[markdown]
highlight_code = false

[extra]
katex = true

anpu_menu_links = [
    { url = "$BASE_URL/about/", name = "About" },
]